version: '3'

services: 
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD="123456"
    volumes:
      - /root/Data/:/var/lib/mysql
    ports:
      - 3306:3306

  web:
    build: ./Flask
    depends_on:
      - db
    links:
      - db
      - db:db4
    environment:
      - DB4_PORT_3306_TCP_ADDR="172.19.0.2"
      - DB4_PORT_3306_TCP_PORT="3306"
      - DB4_ENV_MYSQL_ROOT_PASSWORD="123456"
    command: gunicorn -c gunicorn.py run:app
    ports:
      - "5000:5000"
  
  nginx:
    build: ./nginx
    depends_on:
      - web
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"