version: '3'

services: 
  mysql:
    image: mysql:5.7
    environment:
       MYSQL_ROOT_PASSWORD: "123456"
       MYSQL_DATABASE: "blog"
       MYSQL_USER: "root"
       MYSQL_PASSWORD: "123456"
    volumes:
      - /root/Data:/var/lib/mysql
    ports:
      - "3306:3306"
    expose:
      - "3306"

  web:
    build: ./Flask
    depends_on:
      - mysql
    links:
      - mysql
    command: gunicorn -c gunicorn.py run:app
    ports:
      - "5000:5000"
    expose:
      - "5000"
  
  nginx:
    build: ./nginx
    depends_on:
      - web
    command: nginx -g 'daemon off;'
    ports:
      - "80:80"