
runtime: python37

handlers:
- url: /static
  static_dir: Blog/static
- url: /.*
  script: auto

env_variables:
  CLOUDSQL_CONNECTION_NAME: pythonfun-219016:us-central1:pythonmysql
  CLOUDSQL_USER: root
  CLOUDSQL_PASSWORD: lieon1992316
