version: '3'

services: 
  web:
    build: .
    command: gunicorn -c gunicorn.py run:app
    ports:
      - "5000:5000"
  
  # nginx:
  #   build: ./nginx
  #   depends_on:
  #     - web
  #   command: nginx -g 'daemon off;'
  #   ports:
  #     - "80:80"